version: 2.1

orbs:
  node: circleci/node@5.1.0

jobs:
  install:
    docker:
      - image: cimg/node:16.14
    steps:
      - checkout
      - run: sudo npm install -g lerna@6.4.1
      - restore_node_modules
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Lerna Bootstrap
          command: npx lerna bootstrap
      - save_cache:
          key: v1-deps-{{ checksum "package-lock.json" }}-{{ checksum "combined-package-lock.txt" }}-test1
          paths:
            - node_modules
            - packages/codegen-ui/node_modules
            - packages/codegen-ui-react/node_modules
            - packages/test-generator/node_modules

  style:
    docker:
      - image: cimg/node:16.14
    steps:
      - checkout
      - restore_node_modules
      - run:
          name: Prettier
          command: npm run format:check
      - run:
          name: ESLint
          command: npm run lint
      - run:
          name: Commit Message
          command: |
            echo `git log --format=%s -n 1 $CIRCLE_SHA1` > commit-message-tmp
            ./.husky/commit-msg commit-message-tmp
            rm commit-message-tmp

  build:
    docker:
      - image: cimg/node:16.14
    steps:
      - checkout
      - restore_node_modules
      - run: npm run build
      - save_cache:
          key: dist-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - packages/codegen-ui/dist
            - packages/codegen-ui-react/dist
            - packages/test-generator/dist

  unit-test:
    docker:
      - image: cimg/node:16.14
    resource_class: large
    steps:
      - checkout
      - restore_node_modules
      - run:
          name: Unit Test
          command: npm run test:ci
      - run:
          name: Codecov
          command: npx codecov

  publish:
    docker:
      - image: cimg/node:16.14
    steps:
      - checkout
      - restore_node_modules
      - restore_cache:
          keys:
            - dist-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: NPM Login
          command: npm set "//registry.npmjs.org/:_authToken" $NPM_ACCESS_TOKEN
      - run:
          name: NPM Publish
          command: bash ./.circleci/publish.sh

workflows:
  build:
    jobs:
      - install
      - style:
          requires:
            - install
      - build:
          requires:
            - install
      - unit-test:
          requires:
            - install
      - publish:
          requires:
            - style
            - build
            - unit-test
          filters:
            branches:
              only:
                - main
                - develop
                - /tagged-release\/.*/

commands:
  create_concatenated_package_lock:
    description: 'Concatenate all package-lock.json files recognized by lerna.js into single file. File is used as checksum source for part of caching key.'
    parameters:
      filename:
        type: string
    steps:
      - run:
          name: Combine package-lock.json files to single file
          command: npx lerna@6.4.1 la -a | awk -F packages '{gsub("\\(PRIVATE\\)", "");gsub(" ", "");printf "\"packages%s/package-lock.json\" ", $2}' | xargs cat > << parameters.filename >>

  restore_node_modules:
    description: 'Restore node_modules cache using concatenated package-lock.'
    steps:
      - create_concatenated_package_lock:
          filename: combined-package-lock.txt
      - restore_cache:
          keys:
            - v1-deps-{{ checksum "package-lock.json" }}-{{ checksum "combined-package-lock.txt" }}-test1
