export { default as BoxGolden } from './boxGolden.json';
export { default as BoxTest } from './boxTest.json';
export { default as ButtonGolden } from './buttonGolden.json';
export { default as CustomChild } from './customChild.json';
export { default as DataBindingWithDataStore } from './dataBindingWithDataStore.json';
export { default as ExposedAsTest } from './exposedAsTest.json';
export { default as HeaderWithAction } from './headerWithAction.json';
export { default as SampleCodeSnippet } from './sampleCodeSnippet.json';
export { default as TextGolden } from './textGolden.json';
