/*
  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.

  Licensed under the Apache License, Version 2.0 (the "License").
  You may not use this file except in compliance with the License.
  You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
 */
import { factory, NodeFlags, SyntaxKind } from 'typescript';
import { FieldConfigMetadata, GenericDataRelationshipType, HasManyRelationshipType } from '@aws-amplify/codegen-ui';
import { getRecordsName, getLinkedDataName } from './form-state';
import { buildBaseCollectionVariableStatement } from '../../react-studio-template-renderer-helper';
import { ImportCollection, ImportSource } from '../../imports';
import { lowerCaseFirst } from '../../helpers';

export const buildRelationshipQuery = (
  relationship: GenericDataRelationshipType,
  importCollection: ImportCollection,
) => {
  const { relatedModelName } = relationship;
  const itemsName = getRecordsName(relatedModelName);
  const objectProperties = [
    factory.createPropertyAssignment(factory.createIdentifier('type'), factory.createStringLiteral('collection')),
    factory.createPropertyAssignment(
      factory.createIdentifier('model'),
      factory.createIdentifier(importCollection.getMappedAlias(ImportSource.LOCAL_MODELS, relatedModelName)),
    ),
  ];
  return buildBaseCollectionVariableStatement(
    itemsName,
    factory.createCallExpression(factory.createIdentifier('useDataStoreBinding'), undefined, [
      factory.createObjectLiteralExpression(objectProperties, true),
    ]),
  );
};

export const buildManyToManyRelationshipCreateStatements = (
  dataStoreActionType: 'update' | 'create',
  modelName: string,
  hasManyFieldConfig: [string, FieldConfigMetadata],
) => {
  const [fieldName, fieldConfigMetaData] = hasManyFieldConfig;
  const { relatedModelField, relatedJoinFieldName, relatedJoinTableName } =
    fieldConfigMetaData.relationship as HasManyRelationshipType;
  if (dataStoreActionType === 'update') {
    const linkedDataName = getLinkedDataName(fieldName);
    const dataToLinkMap = `${lowerCaseFirst(fieldName)}ToLinkMap`;
    const dataToUnlinkMap = `${lowerCaseFirst(fieldName)}ToUnLinkMap`;
    const updatedMap = `${lowerCaseFirst(fieldName)}Map`;
    const originalMap = `${linkedDataName}Map`;
    return [
      factory.createVariableStatement(
        undefined,
        factory.createVariableDeclarationList(
          [
            factory.createVariableDeclaration(
              factory.createIdentifier(dataToLinkMap),
              undefined,
              undefined,
              factory.createNewExpression(factory.createIdentifier('Map'), undefined, []),
            ),
          ],
          NodeFlags.Const,
        ),
      ),
      factory.createVariableStatement(
        undefined,
        factory.createVariableDeclarationList(
          [
            factory.createVariableDeclaration(
              factory.createIdentifier(dataToUnlinkMap),
              undefined,
              undefined,
              factory.createNewExpression(factory.createIdentifier('Map'), undefined, []),
            ),
          ],
          NodeFlags.Const,
        ),
      ),
      factory.createVariableStatement(
        undefined,
        factory.createVariableDeclarationList(
          [
            factory.createVariableDeclaration(
              factory.createIdentifier(updatedMap),
              undefined,
              undefined,
              factory.createNewExpression(factory.createIdentifier('Map'), undefined, []),
            ),
          ],
          NodeFlags.Const,
        ),
      ),
      factory.createVariableStatement(
        undefined,
        factory.createVariableDeclarationList(
          [
            factory.createVariableDeclaration(
              factory.createIdentifier(originalMap),
              undefined,
              undefined,
              factory.createNewExpression(factory.createIdentifier('Map'), undefined, []),
            ),
          ],
          NodeFlags.Const,
        ),
      ),
      factory.createExpressionStatement(
        factory.createCallExpression(
          factory.createPropertyAccessExpression(
            factory.createIdentifier(fieldName),
            factory.createIdentifier('forEach'),
          ),
          undefined,
          [
            factory.createArrowFunction(
              undefined,
              undefined,
              [
                factory.createParameterDeclaration(
                  undefined,
                  undefined,
                  undefined,
                  factory.createIdentifier('r'),
                  undefined,
                  undefined,
                  undefined,
                ),
              ],
              undefined,
              factory.createToken(SyntaxKind.EqualsGreaterThanToken),
              factory.createBlock(
                [
                  factory.createVariableStatement(
                    undefined,
                    factory.createVariableDeclarationList(
                      [
                        factory.createVariableDeclaration(
                          factory.createIdentifier('count'),
                          undefined,
                          undefined,
                          factory.createCallExpression(
                            factory.createPropertyAccessExpression(
                              factory.createIdentifier(updatedMap),
                              factory.createIdentifier('get'),
                            ),
                            undefined,
                            [
                              factory.createPropertyAccessExpression(
                                factory.createIdentifier('r'),
                                factory.createIdentifier('id'),
                              ),
                            ],
                          ),
                        ),
                      ],
                      NodeFlags.Const,
                    ),
                  ),
                  factory.createVariableStatement(
                    undefined,
                    factory.createVariableDeclarationList(
                      [
                        factory.createVariableDeclaration(
                          factory.createIdentifier('newCount'),
                          undefined,
                          undefined,
                          factory.createConditionalExpression(
                            factory.createIdentifier('count'),
                            factory.createToken(SyntaxKind.QuestionToken),
                            factory.createBinaryExpression(
                              factory.createIdentifier('count'),
                              factory.createToken(SyntaxKind.PlusToken),
                              factory.createNumericLiteral('1'),
                            ),
                            factory.createToken(SyntaxKind.ColonToken),
                            factory.createNumericLiteral('1'),
                          ),
                        ),
                      ],
                      NodeFlags.Const,
                    ),
                  ),
                  factory.createExpressionStatement(
                    factory.createCallExpression(
                      factory.createPropertyAccessExpression(
                        factory.createIdentifier(updatedMap),
                        factory.createIdentifier('set'),
                      ),
                      undefined,
                      [
                        factory.createPropertyAccessExpression(
                          factory.createIdentifier('r'),
                          factory.createIdentifier('id'),
                        ),
                        factory.createIdentifier('newCount'),
                      ],
                    ),
                  ),
                ],
                true,
              ),
            ),
          ],
        ),
      ),
      factory.createExpressionStatement(
        factory.createCallExpression(
          factory.createPropertyAccessExpression(
            factory.createIdentifier(linkedDataName),
            factory.createIdentifier('forEach'),
          ),
          undefined,
          [
            factory.createArrowFunction(
              undefined,
              undefined,
              [
                factory.createParameterDeclaration(
                  undefined,
                  undefined,
                  undefined,
                  factory.createIdentifier('r'),
                  undefined,
                  undefined,
                  undefined,
                ),
              ],
              undefined,
              factory.createToken(SyntaxKind.EqualsGreaterThanToken),
              factory.createBlock(
                [
                  factory.createVariableStatement(
                    undefined,
                    factory.createVariableDeclarationList(
                      [
                        factory.createVariableDeclaration(
                          factory.createIdentifier('count'),
                          undefined,
                          undefined,
                          factory.createCallExpression(
                            factory.createPropertyAccessExpression(
                              factory.createIdentifier(originalMap),
                              factory.createIdentifier('get'),
                            ),
                            undefined,
                            [
                              factory.createPropertyAccessExpression(
                                factory.createIdentifier('r'),
                                factory.createIdentifier('id'),
                              ),
                            ],
                          ),
                        ),
                      ],
                      NodeFlags.Const,
                    ),
                  ),
                  factory.createVariableStatement(
                    undefined,
                    factory.createVariableDeclarationList(
                      [
                        factory.createVariableDeclaration(
                          factory.createIdentifier('newCount'),
                          undefined,
                          undefined,
                          factory.createConditionalExpression(
                            factory.createIdentifier('count'),
                            factory.createToken(SyntaxKind.QuestionToken),
                            factory.createBinaryExpression(
                              factory.createIdentifier('count'),
                              factory.createToken(SyntaxKind.PlusToken),
                              factory.createNumericLiteral('1'),
                            ),
                            factory.createToken(SyntaxKind.ColonToken),
                            factory.createNumericLiteral('1'),
                          ),
                        ),
                      ],
                      NodeFlags.Const,
                    ),
                  ),
                  factory.createExpressionStatement(
                    factory.createCallExpression(
                      factory.createPropertyAccessExpression(
                        factory.createIdentifier(originalMap),
                        factory.createIdentifier('set'),
                      ),
                      undefined,
                      [
                        factory.createPropertyAccessExpression(
                          factory.createIdentifier('r'),
                          factory.createIdentifier('id'),
                        ),
                        factory.createIdentifier('newCount'),
                      ],
                    ),
                  ),
                ],
                true,
              ),
            ),
          ],
        ),
      ),
      factory.createExpressionStatement(
        factory.createCallExpression(
          factory.createPropertyAccessExpression(
            factory.createIdentifier(originalMap),
            factory.createIdentifier('forEach'),
          ),
          undefined,
          [
            factory.createArrowFunction(
              undefined,
              undefined,
              [
                factory.createParameterDeclaration(
                  undefined,
                  undefined,
                  undefined,
                  factory.createIdentifier('count'),
                  undefined,
                  undefined,
                  undefined,
                ),
                factory.createParameterDeclaration(
                  undefined,
                  undefined,
                  undefined,
                  factory.createIdentifier('id'),
                  undefined,
                  undefined,
                  undefined,
                ),
              ],
              undefined,
              factory.createToken(SyntaxKind.EqualsGreaterThanToken),
              factory.createBlock(
                [
                  factory.createVariableStatement(
                    undefined,
                    factory.createVariableDeclarationList(
                      [
                        factory.createVariableDeclaration(
                          factory.createIdentifier('newCount'),
                          undefined,
                          undefined,
                          factory.createCallExpression(
                            factory.createPropertyAccessExpression(
                              factory.createIdentifier(updatedMap),
                              factory.createIdentifier('get'),
                            ),
                            undefined,
                            [factory.createIdentifier('id')],
                          ),
                        ),
                      ],
                      NodeFlags.Const,
                    ),
                  ),
                  factory.createIfStatement(
                    factory.createIdentifier('newCount'),
                    factory.createBlock(
                      [
                        factory.createVariableStatement(
                          undefined,
                          factory.createVariableDeclarationList(
                            [
                              factory.createVariableDeclaration(
                                factory.createIdentifier('diffCount'),
                                undefined,
                                undefined,
                                factory.createBinaryExpression(
                                  factory.createIdentifier('count'),
                                  factory.createToken(SyntaxKind.MinusToken),
                                  factory.createIdentifier('newCount'),
                                ),
                              ),
                            ],
                            NodeFlags.Const,
                          ),
                        ),
                        factory.createIfStatement(
                          factory.createBinaryExpression(
                            factory.createIdentifier('diffCount'),
                            factory.createToken(SyntaxKind.GreaterThanToken),
                            factory.createNumericLiteral('0'),
                          ),
                          factory.createBlock(
                            [
                              factory.createExpressionStatement(
                                factory.createCallExpression(
                                  factory.createPropertyAccessExpression(
                                    factory.createIdentifier(dataToUnlinkMap),
                                    factory.createIdentifier('set'),
                                  ),
                                  undefined,
                                  [factory.createIdentifier('id'), factory.createIdentifier('diffCount')],
                                ),
                              ),
                            ],
                            true,
                          ),
                          undefined,
                        ),
                      ],
                      true,
                    ),
                    factory.createBlock(
                      [
                        factory.createExpressionStatement(
                          factory.createCallExpression(
                            factory.createPropertyAccessExpression(
                              factory.createIdentifier(dataToUnlinkMap),
                              factory.createIdentifier('set'),
                            ),
                            undefined,
                            [factory.createIdentifier('id'), factory.createIdentifier('count')],
                          ),
                        ),
                      ],
                      true,
                    ),
                  ),
                ],
                true,
              ),
            ),
          ],
        ),
      ),
      factory.createExpressionStatement(
        factory.createCallExpression(
          factory.createPropertyAccessExpression(
            factory.createIdentifier(updatedMap),
            factory.createIdentifier('forEach'),
          ),
          undefined,
          [
            factory.createArrowFunction(
              undefined,
              undefined,
              [
                factory.createParameterDeclaration(
                  undefined,
                  undefined,
                  undefined,
                  factory.createIdentifier('count'),
                  undefined,
                  undefined,
                  undefined,
                ),
                factory.createParameterDeclaration(
                  undefined,
                  undefined,
                  undefined,
                  factory.createIdentifier('id'),
                  undefined,
                  undefined,
                  undefined,
                ),
              ],
              undefined,
              factory.createToken(SyntaxKind.EqualsGreaterThanToken),
              factory.createBlock(
                [
                  factory.createVariableStatement(
                    undefined,
                    factory.createVariableDeclarationList(
                      [
                        factory.createVariableDeclaration(
                          factory.createIdentifier('originalCount'),
                          undefined,
                          undefined,
                          factory.createCallExpression(
                            factory.createPropertyAccessExpression(
                              factory.createIdentifier(originalMap),
                              factory.createIdentifier('get'),
                            ),
                            undefined,
                            [factory.createIdentifier('id')],
                          ),
                        ),
                      ],
                      NodeFlags.Const,
                    ),
                  ),
                  factory.createIfStatement(
                    factory.createIdentifier('originalCount'),
                    factory.createBlock(
                      [
                        factory.createVariableStatement(
                          undefined,
                          factory.createVariableDeclarationList(
                            [
                              factory.createVariableDeclaration(
                                factory.createIdentifier('diffCount'),
                                undefined,
                                undefined,
                                factory.createBinaryExpression(
                                  factory.createIdentifier('count'),
                                  factory.createToken(SyntaxKind.MinusToken),
                                  factory.createIdentifier('originalCount'),
                                ),
                              ),
                            ],
                            NodeFlags.Const,
                          ),
                        ),
                        factory.createIfStatement(
                          factory.createBinaryExpression(
                            factory.createIdentifier('diffCount'),
                            factory.createToken(SyntaxKind.GreaterThanToken),
                            factory.createNumericLiteral('0'),
                          ),
                          factory.createBlock(
                            [
                              factory.createExpressionStatement(
                                factory.createCallExpression(
                                  factory.createPropertyAccessExpression(
                                    factory.createIdentifier(dataToLinkMap),
                                    factory.createIdentifier('set'),
                                  ),
                                  undefined,
                                  [factory.createIdentifier('id'), factory.createIdentifier('diffCount')],
                                ),
                              ),
                            ],
                            true,
                          ),
                          undefined,
                        ),
                      ],
                      true,
                    ),
                    factory.createBlock(
                      [
                        factory.createExpressionStatement(
                          factory.createCallExpression(
                            factory.createPropertyAccessExpression(
                              factory.createIdentifier(dataToLinkMap),
                              factory.createIdentifier('set'),
                            ),
                            undefined,
                            [factory.createIdentifier('id'), factory.createIdentifier('count')],
                          ),
                        ),
                      ],
                      true,
                    ),
                  ),
                ],
                true,
              ),
            ),
          ],
        ),
      ),
      factory.createVariableStatement(
        undefined,
        factory.createVariableDeclarationList(
          [
            factory.createVariableDeclaration(
              factory.createIdentifier('promises'),
              undefined,
              undefined,
              factory.createArrayLiteralExpression([], false),
            ),
          ],
          NodeFlags.Const,
        ),
      ),
      factory.createExpressionStatement(
        factory.createCallExpression(
          factory.createPropertyAccessExpression(
            factory.createIdentifier(dataToUnlinkMap),
            factory.createIdentifier('forEach'),
          ),
          undefined,
          [
            factory.createArrowFunction(
              [factory.createModifier(SyntaxKind.AsyncKeyword)],
              undefined,
              [
                factory.createParameterDeclaration(
                  undefined,
                  undefined,
                  undefined,
                  factory.createIdentifier('count'),
                  undefined,
                  undefined,
                  undefined,
                ),
                factory.createParameterDeclaration(
                  undefined,
                  undefined,
                  undefined,
                  factory.createIdentifier('id'),
                  undefined,
                  undefined,
                  undefined,
                ),
              ],
              undefined,
              factory.createToken(SyntaxKind.EqualsGreaterThanToken),
              factory.createBlock(
                [
                  factory.createVariableStatement(
                    undefined,
                    factory.createVariableDeclarationList(
                      [
                        factory.createVariableDeclaration(
                          factory.createIdentifier(getRecordsName(relatedJoinTableName as string)),
                          undefined,
                          undefined,
                          factory.createAwaitExpression(
                            factory.createCallExpression(
                              factory.createPropertyAccessExpression(
                                factory.createIdentifier('DataStore'),
                                factory.createIdentifier('query'),
                              ),
                              undefined,
                              [
                                factory.createIdentifier(relatedJoinTableName as string),
                                factory.createArrowFunction(
                                  undefined,
                                  undefined,
                                  [
                                    factory.createParameterDeclaration(
                                      undefined,
                                      undefined,
                                      undefined,
                                      factory.createIdentifier('r'),
                                      undefined,
                                      undefined,
                                      undefined,
                                    ),
                                  ],
                                  undefined,
                                  factory.createToken(SyntaxKind.EqualsGreaterThanToken),
                                  factory.createCallExpression(
                                    factory.createPropertyAccessExpression(
                                      factory.createIdentifier('r'),
                                      factory.createIdentifier('and'),
                                    ),
                                    undefined,
                                    [
                                      factory.createArrowFunction(
                                        undefined,
                                        undefined,
                                        [
                                          factory.createParameterDeclaration(
                                            undefined,
                                            undefined,
                                            undefined,
                                            factory.createIdentifier('r'),
                                            undefined,
                                            undefined,
                                            undefined,
                                          ),
                                        ],
                                        undefined,
                                        factory.createToken(SyntaxKind.EqualsGreaterThanToken),
                                        factory.createArrayLiteralExpression(
                                          [
                                            factory.createCallExpression(
                                              factory.createPropertyAccessExpression(
                                                factory.createPropertyAccessExpression(
                                                  factory.createPropertyAccessExpression(
                                                    factory.createIdentifier('r'),
                                                    factory.createIdentifier(relatedJoinFieldName as string),
                                                  ),
                                                  factory.createIdentifier('id'),
                                                ),
                                                factory.createIdentifier('eq'),
                                              ),
                                              undefined,
                                              [factory.createIdentifier('id')],
                                            ),
                                            factory.createCallExpression(
                                              factory.createPropertyAccessExpression(
                                                factory.createPropertyAccessExpression(
                                                  factory.createPropertyAccessExpression(
                                                    factory.createIdentifier('r'),
                                                    factory.createIdentifier(relatedModelField as string),
                                                  ),
                                                  factory.createIdentifier('id'),
                                                ),
                                                factory.createIdentifier('eq'),
                                              ),
                                              undefined,
                                              [
                                                factory.createPropertyAccessExpression(
                                                  factory.createIdentifier(`${lowerCaseFirst(modelName)}Record`),
                                                  factory.createIdentifier('id'),
                                                ),
                                              ],
                                            ),
                                          ],
                                          false,
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ],
                            ),
                          ),
                        ),
                      ],
                      // eslint-disable-next-line no-bitwise
                      NodeFlags.Const | NodeFlags.AwaitContext | NodeFlags.ContextFlags | NodeFlags.TypeExcludesFlags,
                    ),
                  ),
                  factory.createForStatement(
                    factory.createVariableDeclarationList(
                      [
                        factory.createVariableDeclaration(
                          factory.createIdentifier('i'),
                          undefined,
                          undefined,
                          factory.createNumericLiteral('0'),
                        ),
                      ],
                      // eslint-disable-next-line no-bitwise
                      NodeFlags.Let | NodeFlags.AwaitContext | NodeFlags.ContextFlags | NodeFlags.TypeExcludesFlags,
                    ),
                    factory.createBinaryExpression(
                      factory.createIdentifier('i'),
                      factory.createToken(SyntaxKind.LessThanToken),
                      factory.createIdentifier('count'),
                    ),
                    factory.createPostfixUnaryExpression(factory.createIdentifier('i'), SyntaxKind.PlusPlusToken),
                    factory.createBlock(
                      [
                        factory.createExpressionStatement(
                          factory.createCallExpression(
                            factory.createPropertyAccessExpression(
                              factory.createIdentifier('promises'),
                              factory.createIdentifier('push'),
                            ),
                            undefined,
                            [
                              factory.createCallExpression(
                                factory.createPropertyAccessExpression(
                                  factory.createIdentifier('DataStore'),
                                  factory.createIdentifier('delete'),
                                ),
                                undefined,
                                [
                                  factory.createElementAccessExpression(
                                    factory.createIdentifier(getRecordsName(relatedJoinTableName as string)),
                                    factory.createIdentifier('i'),
                                  ),
                                ],
                              ),
                            ],
                          ),
                        ),
                      ],
                      true,
                    ),
                  ),
                ],
                true,
              ),
            ),
          ],
        ),
      ),
      factory.createExpressionStatement(
        factory.createCallExpression(
          factory.createPropertyAccessExpression(
            factory.createIdentifier(dataToLinkMap),
            factory.createIdentifier('forEach'),
          ),
          undefined,
          [
            factory.createArrowFunction(
              undefined,
              undefined,
              [
                factory.createParameterDeclaration(
                  undefined,
                  undefined,
                  undefined,
                  factory.createIdentifier('count'),
                  undefined,
                  undefined,
                  undefined,
                ),
                factory.createParameterDeclaration(
                  undefined,
                  undefined,
                  undefined,
                  factory.createIdentifier('id'),
                  undefined,
                  undefined,
                  undefined,
                ),
              ],
              undefined,
              factory.createToken(SyntaxKind.EqualsGreaterThanToken),
              factory.createBlock(
                [
                  factory.createForStatement(
                    factory.createVariableDeclarationList(
                      [
                        factory.createVariableDeclaration(
                          factory.createIdentifier('i'),
                          undefined,
                          undefined,
                          factory.createIdentifier('count'),
                        ),
                      ],
                      NodeFlags.Let,
                    ),
                    factory.createBinaryExpression(
                      factory.createIdentifier('i'),
                      factory.createToken(SyntaxKind.GreaterThanToken),
                      factory.createNumericLiteral('0'),
                    ),
                    factory.createPostfixUnaryExpression(factory.createIdentifier('i'), SyntaxKind.MinusMinusToken),
                    factory.createBlock(
                      [
                        factory.createExpressionStatement(
                          factory.createCallExpression(
                            factory.createPropertyAccessExpression(
                              factory.createIdentifier('promises'),
                              factory.createIdentifier('push'),
                            ),
                            undefined,
                            [
                              factory.createCallExpression(
                                factory.createPropertyAccessExpression(
                                  factory.createIdentifier('DataStore'),
                                  factory.createIdentifier('save'),
                                ),
                                undefined,
                                [
                                  factory.createNewExpression(
                                    factory.createIdentifier(relatedJoinTableName as string),
                                    undefined,
                                    [
                                      factory.createObjectLiteralExpression(
                                        [
                                          factory.createPropertyAssignment(
                                            factory.createIdentifier(`${relatedModelField}ID`),
                                            factory.createPropertyAccessExpression(
                                              factory.createIdentifier(`${lowerCaseFirst(modelName)}Record`),
                                              factory.createIdentifier('id'),
                                            ),
                                          ),
                                          factory.createPropertyAssignment(
                                            factory.createIdentifier(`${relatedJoinFieldName}ID`),
                                            factory.createIdentifier('id'),
                                          ),
                                        ],
                                        true,
                                      ),
                                    ],
                                  ),
                                ],
                              ),
                            ],
                          ),
                        ),
                      ],
                      true,
                    ),
                  ),
                ],
                true,
              ),
            ),
          ],
        ),
      ),
      factory.createExpressionStatement(
        factory.createCallExpression(
          factory.createPropertyAccessExpression(
            factory.createIdentifier('promises'),
            factory.createIdentifier('push'),
          ),
          undefined,
          [
            factory.createCallExpression(
              factory.createPropertyAccessExpression(
                factory.createIdentifier('DataStore'),
                factory.createIdentifier('save'),
              ),
              undefined,
              [
                factory.createCallExpression(
                  factory.createPropertyAccessExpression(
                    factory.createIdentifier(modelName),
                    factory.createIdentifier('copyOf'),
                  ),
                  undefined,
                  [
                    factory.createIdentifier(`${lowerCaseFirst(modelName)}Record`),
                    factory.createArrowFunction(
                      undefined,
                      undefined,
                      [
                        factory.createParameterDeclaration(
                          undefined,
                          undefined,
                          undefined,
                          factory.createIdentifier('updated'),
                          undefined,
                          undefined,
                          undefined,
                        ),
                      ],
                      undefined,
                      factory.createToken(SyntaxKind.EqualsGreaterThanToken),
                      factory.createBlock(
                        [
                          factory.createExpressionStatement(
                            factory.createCallExpression(
                              factory.createPropertyAccessExpression(
                                factory.createIdentifier('Object'),
                                factory.createIdentifier('assign'),
                              ),
                              undefined,
                              [factory.createIdentifier('updated'), factory.createIdentifier('modelFields')],
                            ),
                          ),
                        ],
                        true,
                      ),
                    ),
                  ],
                ),
              ],
            ),
          ],
        ),
      ),
      factory.createExpressionStatement(
        factory.createAwaitExpression(
          factory.createCallExpression(
            factory.createPropertyAccessExpression(
              factory.createIdentifier('Promise'),
              factory.createIdentifier('all'),
            ),
            undefined,
            [factory.createIdentifier('promises')],
          ),
        ),
      ),
    ];
  }
  return [
    factory.createVariableStatement(
      undefined,
      factory.createVariableDeclarationList(
        [
          factory.createVariableDeclaration(
            factory.createIdentifier(relatedModelField),
            undefined,
            undefined,
            factory.createAwaitExpression(
              factory.createCallExpression(
                factory.createPropertyAccessExpression(
                  factory.createIdentifier('DataStore'),
                  factory.createIdentifier('save'),
                ),
                undefined,
                [
                  factory.createNewExpression(factory.createIdentifier(modelName), undefined, [
                    factory.createIdentifier('modelFields'),
                  ]),
                ],
              ),
            ),
          ),
        ],
        NodeFlags.Const,
      ),
    ),
    factory.createExpressionStatement(
      factory.createAwaitExpression(
        factory.createCallExpression(
          factory.createPropertyAccessExpression(factory.createIdentifier('Promise'), factory.createIdentifier('all')),
          undefined,
          [
            factory.createCallExpression(
              factory.createPropertyAccessExpression(
                factory.createIdentifier(fieldName),
                factory.createIdentifier('reduce'),
              ),
              undefined,
              [
                factory.createArrowFunction(
                  undefined,
                  undefined,
                  [
                    factory.createParameterDeclaration(
                      undefined,
                      undefined,
                      undefined,
                      factory.createIdentifier('promises'),
                      undefined,
                      undefined,
                      undefined,
                    ),
                    factory.createParameterDeclaration(
                      undefined,
                      undefined,
                      undefined,
                      factory.createIdentifier(relatedJoinFieldName as string),
                      undefined,
                      undefined,
                      undefined,
                    ),
                  ],
                  undefined,
                  factory.createToken(SyntaxKind.EqualsGreaterThanToken),
                  factory.createBlock(
                    [
                      factory.createExpressionStatement(
                        factory.createCallExpression(
                          factory.createPropertyAccessExpression(
                            factory.createIdentifier('promises'),
                            factory.createIdentifier('push'),
                          ),
                          undefined,
                          [
                            factory.createCallExpression(
                              factory.createPropertyAccessExpression(
                                factory.createIdentifier('DataStore'),
                                factory.createIdentifier('save'),
                              ),
                              undefined,
                              [
                                factory.createNewExpression(
                                  factory.createIdentifier(relatedJoinTableName as string),
                                  undefined,
                                  [
                                    factory.createObjectLiteralExpression(
                                      [
                                        factory.createShorthandPropertyAssignment(
                                          factory.createIdentifier(relatedModelField),
                                          undefined,
                                        ),
                                        factory.createShorthandPropertyAssignment(
                                          factory.createIdentifier(relatedJoinFieldName as string),
                                          undefined,
                                        ),
                                      ],
                                      true,
                                    ),
                                  ],
                                ),
                              ],
                            ),
                          ],
                        ),
                      ),
                      factory.createReturnStatement(factory.createIdentifier('promises')),
                    ],
                    true,
                  ),
                ),
                factory.createArrayLiteralExpression([], false),
              ],
            ),
          ],
        ),
      ),
    ),
  ];
};

export const buildGetRelationshipModels = (fieldName: string, recordName: string) => {
  return [
    factory.createVariableStatement(
      undefined,
      factory.createVariableDeclarationList(
        [
          factory.createVariableDeclaration(
            factory.createIdentifier('getRelationshipModel'),
            undefined,
            undefined,
            factory.createArrowFunction(
              [factory.createModifier(SyntaxKind.AsyncKeyword)],
              undefined,
              [],
              undefined,
              factory.createToken(SyntaxKind.EqualsGreaterThanToken),
              factory.createBlock(
                [
                  factory.createIfStatement(
                    factory.createIdentifier(recordName),
                    factory.createBlock(
                      [
                        factory.createExpressionStatement(
                          factory.createCallExpression(factory.createIdentifier(`set${fieldName}`), undefined, [
                            factory.createAwaitExpression(
                              factory.createPropertyAccessExpression(
                                factory.createIdentifier(recordName),
                                factory.createIdentifier(fieldName),
                              ),
                            ),
                          ]),
                        ),
                      ],
                      true,
                    ),
                    undefined,
                  ),
                ],
                true,
              ),
            ),
          ),
        ],
        NodeFlags.Const,
      ),
    ),
    factory.createExpressionStatement(
      factory.createCallExpression(factory.createIdentifier('getRelationshipModel'), undefined, []),
    ),
  ];
};
