/*
  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.

  Licensed under the Apache License, Version 2.0 (the "License").
  You may not use this file except in compliance with the License.
  You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
 */
import { factory, NodeFlags, SyntaxKind } from 'typescript';
import { FieldConfigMetadata, GenericDataRelationshipType, HasManyRelationshipType } from '@aws-amplify/codegen-ui';
import { getRecordsName, getLinkedRecordsName } from './form-state';
import { buildBaseCollectionVariableStatement } from '../../react-studio-template-renderer-helper';
import { ImportCollection, ImportSource } from '../../imports';

export const buildRelationshipQuery = (
  relationship: GenericDataRelationshipType,
  importCollection: ImportCollection,
) => {
  const { relatedModelName } = relationship;
  const itemsName = getRecordsName(relatedModelName);
  const objectProperties = [
    factory.createPropertyAssignment(factory.createIdentifier('type'), factory.createStringLiteral('collection')),
    factory.createPropertyAssignment(
      factory.createIdentifier('model'),
      factory.createIdentifier(importCollection.getMappedAlias(ImportSource.LOCAL_MODELS, relatedModelName)),
    ),
  ];
  return buildBaseCollectionVariableStatement(
    itemsName,
    factory.createCallExpression(factory.createIdentifier('useDataStoreBinding'), undefined, [
      factory.createObjectLiteralExpression(objectProperties, true),
    ]),
  );
};

export const buildManyToManyRelationshipCreateStatements = (
  dataStoreActionType: 'update' | 'create',
  modelName: string,
  hasManyFieldConfig: [string, FieldConfigMetadata],
) => {
  const [fieldName, fieldConfigMetaData] = hasManyFieldConfig;
  const { relatedModelField, relatedJoinFieldName, relatedJoinTableName } =
    fieldConfigMetaData.relationship as HasManyRelationshipType;
  if (dataStoreActionType === 'update') {
    const linkedRecordsName = getLinkedRecordsName(fieldName);
    const dataToLink = `${fieldName.toLowerCase()}ToLink`;
    const dataToUnlink = `${fieldName.toLowerCase()}ToUnLink`;
    const updatedSet = `${fieldName.toLowerCase()}Set`;
    const originalSet = `${linkedRecordsName}Set`;
    return [
      factory.createVariableStatement(
        undefined,
        factory.createVariableDeclarationList(
          [
            factory.createVariableDeclaration(
              factory.createIdentifier(dataToLink),
              undefined,
              undefined,
              factory.createArrayLiteralExpression([], false),
            ),
          ],
          NodeFlags.Const,
        ),
      ),
      factory.createVariableStatement(
        undefined,
        factory.createVariableDeclarationList(
          [
            factory.createVariableDeclaration(
              factory.createIdentifier(dataToUnlink),
              undefined,
              undefined,
              factory.createArrayLiteralExpression([], false),
            ),
          ],
          NodeFlags.Const,
        ),
      ),
      factory.createVariableStatement(
        undefined,
        factory.createVariableDeclarationList(
          [
            factory.createVariableDeclaration(
              factory.createIdentifier(updatedSet),
              undefined,
              undefined,
              factory.createNewExpression(factory.createIdentifier('Set'), undefined, []),
            ),
          ],
          NodeFlags.Const,
        ),
      ),
      factory.createVariableStatement(
        undefined,
        factory.createVariableDeclarationList(
          [
            factory.createVariableDeclaration(
              factory.createIdentifier(originalSet),
              undefined,
              undefined,
              factory.createNewExpression(factory.createIdentifier('Set'), undefined, []),
            ),
          ],
          NodeFlags.Const,
        ),
      ),
      factory.createExpressionStatement(
        factory.createCallExpression(
          factory.createPropertyAccessExpression(
            factory.createIdentifier(fieldName),
            factory.createIdentifier('forEach'),
          ),
          undefined,
          [
            factory.createArrowFunction(
              undefined,
              undefined,
              [
                factory.createParameterDeclaration(
                  undefined,
                  undefined,
                  undefined,
                  factory.createIdentifier('r'),
                  undefined,
                  undefined,
                  undefined,
                ),
              ],
              undefined,
              factory.createToken(SyntaxKind.EqualsGreaterThanToken),
              factory.createCallExpression(
                factory.createPropertyAccessExpression(
                  factory.createIdentifier(updatedSet),
                  factory.createIdentifier('add'),
                ),
                undefined,
                [factory.createPropertyAccessExpression(factory.createIdentifier('r'), factory.createIdentifier('id'))],
              ),
            ),
          ],
        ),
      ),
      factory.createExpressionStatement(
        factory.createCallExpression(
          factory.createPropertyAccessExpression(
            factory.createIdentifier(linkedRecordsName),
            factory.createIdentifier('forEach'),
          ),
          undefined,
          [
            factory.createArrowFunction(
              undefined,
              undefined,
              [
                factory.createParameterDeclaration(
                  undefined,
                  undefined,
                  undefined,
                  factory.createIdentifier('r'),
                  undefined,
                  undefined,
                  undefined,
                ),
              ],
              undefined,
              factory.createToken(SyntaxKind.EqualsGreaterThanToken),
              factory.createCallExpression(
                factory.createPropertyAccessExpression(
                  factory.createIdentifier(originalSet),
                  factory.createIdentifier('add'),
                ),
                undefined,
                [factory.createPropertyAccessExpression(factory.createIdentifier('r'), factory.createIdentifier('id'))],
              ),
            ),
          ],
        ),
      ),
      factory.createExpressionStatement(
        factory.createCallExpression(
          factory.createPropertyAccessExpression(
            factory.createIdentifier(linkedRecordsName),
            factory.createIdentifier('forEach'),
          ),
          undefined,
          [
            factory.createArrowFunction(
              undefined,
              undefined,
              [
                factory.createParameterDeclaration(
                  undefined,
                  undefined,
                  undefined,
                  factory.createIdentifier('r'),
                  undefined,
                  undefined,
                  undefined,
                ),
              ],
              undefined,
              factory.createToken(SyntaxKind.EqualsGreaterThanToken),
              factory.createBlock(
                [
                  factory.createIfStatement(
                    factory.createPrefixUnaryExpression(
                      SyntaxKind.ExclamationToken,
                      factory.createCallExpression(
                        factory.createPropertyAccessExpression(
                          factory.createIdentifier(updatedSet),
                          factory.createIdentifier('has'),
                        ),
                        undefined,
                        [
                          factory.createPropertyAccessExpression(
                            factory.createIdentifier('r'),
                            factory.createIdentifier('id'),
                          ),
                        ],
                      ),
                    ),
                    factory.createBlock(
                      [
                        factory.createExpressionStatement(
                          factory.createCallExpression(
                            factory.createPropertyAccessExpression(
                              factory.createIdentifier(dataToUnlink),
                              factory.createIdentifier('push'),
                            ),
                            undefined,
                            [factory.createIdentifier('r')],
                          ),
                        ),
                      ],
                      true,
                    ),
                    undefined,
                  ),
                ],
                true,
              ),
            ),
          ],
        ),
      ),
      factory.createExpressionStatement(
        factory.createCallExpression(
          factory.createPropertyAccessExpression(
            factory.createIdentifier(fieldName),
            factory.createIdentifier('forEach'),
          ),
          undefined,
          [
            factory.createArrowFunction(
              undefined,
              undefined,
              [
                factory.createParameterDeclaration(
                  undefined,
                  undefined,
                  undefined,
                  factory.createIdentifier('r'),
                  undefined,
                  undefined,
                  undefined,
                ),
              ],
              undefined,
              factory.createToken(SyntaxKind.EqualsGreaterThanToken),
              factory.createBlock(
                [
                  factory.createIfStatement(
                    factory.createPrefixUnaryExpression(
                      SyntaxKind.ExclamationToken,
                      factory.createCallExpression(
                        factory.createPropertyAccessExpression(
                          factory.createIdentifier(originalSet),
                          factory.createIdentifier('has'),
                        ),
                        undefined,
                        [
                          factory.createPropertyAccessExpression(
                            factory.createIdentifier('r'),
                            factory.createIdentifier('id'),
                          ),
                        ],
                      ),
                    ),
                    factory.createBlock(
                      [
                        factory.createExpressionStatement(
                          factory.createCallExpression(
                            factory.createPropertyAccessExpression(
                              factory.createIdentifier(dataToLink),
                              factory.createIdentifier('push'),
                            ),
                            undefined,
                            [factory.createIdentifier('r')],
                          ),
                        ),
                      ],
                      true,
                    ),
                    undefined,
                  ),
                ],
                true,
              ),
            ),
          ],
        ),
      ),
      factory.createVariableStatement(
        undefined,
        factory.createVariableDeclarationList(
          [
            factory.createVariableDeclaration(
              factory.createIdentifier('promises'),
              undefined,
              undefined,
              factory.createArrayLiteralExpression([], false),
            ),
          ],
          NodeFlags.Const,
        ),
      ),
      factory.createExpressionStatement(
        factory.createCallExpression(
          factory.createPropertyAccessExpression(
            factory.createIdentifier('promises'),
            factory.createIdentifier('push'),
          ),
          undefined,
          [
            factory.createSpreadElement(
              factory.createCallExpression(
                factory.createPropertyAccessExpression(
                  factory.createIdentifier(dataToUnlink),
                  factory.createIdentifier('map'),
                ),
                undefined,
                [
                  factory.createArrowFunction(
                    undefined,
                    undefined,
                    [
                      factory.createParameterDeclaration(
                        undefined,
                        undefined,
                        undefined,
                        factory.createIdentifier(relatedJoinFieldName as string),
                        undefined,
                        undefined,
                        undefined,
                      ),
                    ],
                    undefined,
                    factory.createToken(SyntaxKind.EqualsGreaterThanToken),
                    factory.createCallExpression(
                      factory.createPropertyAccessExpression(
                        factory.createIdentifier('DataStore'),
                        factory.createIdentifier('delete'),
                      ),
                      undefined,
                      [
                        factory.createIdentifier(relatedJoinTableName as string),
                        factory.createArrowFunction(
                          undefined,
                          undefined,
                          [
                            factory.createParameterDeclaration(
                              undefined,
                              undefined,
                              undefined,
                              factory.createIdentifier('r'),
                              undefined,
                              undefined,
                              undefined,
                            ),
                          ],
                          undefined,
                          factory.createToken(SyntaxKind.EqualsGreaterThanToken),
                          factory.createCallExpression(
                            factory.createPropertyAccessExpression(
                              factory.createPropertyAccessExpression(
                                factory.createIdentifier('r'),
                                factory.createIdentifier(`${relatedJoinFieldName}ID`),
                              ),
                              factory.createIdentifier('eq'),
                            ),
                            undefined,
                            [
                              factory.createPropertyAccessExpression(
                                factory.createIdentifier(relatedJoinFieldName as string),
                                factory.createIdentifier('id'),
                              ),
                            ],
                          ),
                        ),
                      ],
                    ),
                  ),
                ],
              ),
            ),
          ],
        ),
      ),
      factory.createExpressionStatement(
        factory.createCallExpression(
          factory.createPropertyAccessExpression(
            factory.createIdentifier('promises'),
            factory.createIdentifier('push'),
          ),
          undefined,
          [
            factory.createSpreadElement(
              factory.createCallExpression(
                factory.createPropertyAccessExpression(
                  factory.createIdentifier(dataToLink),
                  factory.createIdentifier('map'),
                ),
                undefined,
                [
                  factory.createArrowFunction(
                    undefined,
                    undefined,
                    [
                      factory.createParameterDeclaration(
                        undefined,
                        undefined,
                        undefined,
                        factory.createIdentifier(relatedJoinFieldName as string),
                        undefined,
                        undefined,
                        undefined,
                      ),
                    ],
                    undefined,
                    factory.createToken(SyntaxKind.EqualsGreaterThanToken),
                    factory.createCallExpression(
                      factory.createPropertyAccessExpression(
                        factory.createIdentifier('DataStore'),
                        factory.createIdentifier('save'),
                      ),
                      undefined,
                      [
                        factory.createNewExpression(
                          factory.createIdentifier(relatedJoinTableName as string),
                          undefined,
                          [
                            factory.createObjectLiteralExpression(
                              [
                                factory.createPropertyAssignment(
                                  factory.createIdentifier(relatedModelField),
                                  factory.createIdentifier(`${relatedModelField}Record`),
                                ),
                                factory.createShorthandPropertyAssignment(
                                  factory.createIdentifier(relatedJoinFieldName as string),
                                  undefined,
                                ),
                              ],
                              true,
                            ),
                          ],
                        ),
                      ],
                    ),
                  ),
                ],
              ),
            ),
          ],
        ),
      ),
      factory.createExpressionStatement(
        factory.createCallExpression(
          factory.createPropertyAccessExpression(
            factory.createIdentifier('promises'),
            factory.createIdentifier('push'),
          ),
          undefined,
          [
            factory.createCallExpression(
              factory.createPropertyAccessExpression(
                factory.createIdentifier('DataStore'),
                factory.createIdentifier('save'),
              ),
              undefined,
              [
                factory.createCallExpression(
                  factory.createPropertyAccessExpression(
                    factory.createIdentifier(modelName),
                    factory.createIdentifier('copyOf'),
                  ),
                  undefined,
                  [
                    factory.createIdentifier(`${relatedModelField}Record`),
                    factory.createArrowFunction(
                      undefined,
                      undefined,
                      [
                        factory.createParameterDeclaration(
                          undefined,
                          undefined,
                          undefined,
                          factory.createIdentifier('updated'),
                          undefined,
                          undefined,
                          undefined,
                        ),
                      ],
                      undefined,
                      factory.createToken(SyntaxKind.EqualsGreaterThanToken),
                      factory.createBlock(
                        [
                          factory.createExpressionStatement(
                            factory.createCallExpression(
                              factory.createPropertyAccessExpression(
                                factory.createIdentifier('Object'),
                                factory.createIdentifier('assign'),
                              ),
                              undefined,
                              [factory.createIdentifier('updated'), factory.createIdentifier('modelFields')],
                            ),
                          ),
                        ],
                        true,
                      ),
                    ),
                  ],
                ),
              ],
            ),
          ],
        ),
      ),
      factory.createExpressionStatement(
        factory.createAwaitExpression(
          factory.createCallExpression(
            factory.createPropertyAccessExpression(
              factory.createIdentifier('Promise'),
              factory.createIdentifier('all'),
            ),
            undefined,
            [factory.createIdentifier('promises')],
          ),
        ),
      ),
    ];
  }
  return [
    factory.createVariableStatement(
      undefined,
      factory.createVariableDeclarationList(
        [
          factory.createVariableDeclaration(
            factory.createIdentifier(relatedModelField),
            undefined,
            undefined,
            factory.createAwaitExpression(
              factory.createCallExpression(
                factory.createPropertyAccessExpression(
                  factory.createIdentifier('DataStore'),
                  factory.createIdentifier('save'),
                ),
                undefined,
                [
                  factory.createNewExpression(factory.createIdentifier(modelName), undefined, [
                    factory.createIdentifier('modelFields'),
                  ]),
                ],
              ),
            ),
          ),
        ],
        NodeFlags.Const,
      ),
    ),
    factory.createExpressionStatement(
      factory.createAwaitExpression(
        factory.createCallExpression(
          factory.createPropertyAccessExpression(factory.createIdentifier('Promise'), factory.createIdentifier('all')),
          undefined,
          [
            factory.createCallExpression(
              factory.createPropertyAccessExpression(
                factory.createIdentifier(fieldName),
                factory.createIdentifier('reduce'),
              ),
              undefined,
              [
                factory.createArrowFunction(
                  undefined,
                  undefined,
                  [
                    factory.createParameterDeclaration(
                      undefined,
                      undefined,
                      undefined,
                      factory.createIdentifier('promises'),
                      undefined,
                      undefined,
                      undefined,
                    ),
                    factory.createParameterDeclaration(
                      undefined,
                      undefined,
                      undefined,
                      factory.createIdentifier(relatedJoinFieldName as string),
                      undefined,
                      undefined,
                      undefined,
                    ),
                  ],
                  undefined,
                  factory.createToken(SyntaxKind.EqualsGreaterThanToken),
                  factory.createBlock(
                    [
                      factory.createExpressionStatement(
                        factory.createCallExpression(
                          factory.createPropertyAccessExpression(
                            factory.createIdentifier('promises'),
                            factory.createIdentifier('push'),
                          ),
                          undefined,
                          [
                            factory.createCallExpression(
                              factory.createPropertyAccessExpression(
                                factory.createIdentifier('DataStore'),
                                factory.createIdentifier('save'),
                              ),
                              undefined,
                              [
                                factory.createNewExpression(
                                  factory.createIdentifier(relatedJoinTableName as string),
                                  undefined,
                                  [
                                    factory.createObjectLiteralExpression(
                                      [
                                        factory.createShorthandPropertyAssignment(
                                          factory.createIdentifier(relatedModelField),
                                          undefined,
                                        ),
                                        factory.createShorthandPropertyAssignment(
                                          factory.createIdentifier(relatedJoinFieldName as string),
                                          undefined,
                                        ),
                                      ],
                                      true,
                                    ),
                                  ],
                                ),
                              ],
                            ),
                          ],
                        ),
                      ),
                      factory.createReturnStatement(factory.createIdentifier('promises')),
                    ],
                    true,
                  ),
                ),
                factory.createArrayLiteralExpression([], false),
              ],
            ),
          ],
        ),
      ),
    ),
  ];
};
