/*
  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.

  Licensed under the Apache License, Version 2.0 (the "License").
  You may not use this file except in compliance with the License.
  You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
 */
import { factory, JsxChild, JsxTagNamePropertyAccess, NodeFlags, SyntaxKind } from 'typescript';
import { capitalizeFirstLetter } from '../../forms/form-state';
import { lowerCaseFirst } from '../../helpers';

export const generateArrayFieldComponent = () => {
  const iconPath = 'M10 10l5.09-5.09L10 10l5.09 5.09L10 10zm0 0L4.91 4.91 10 10l-5.09 5.09L10 10z';
  return factory.createFunctionDeclaration(
    undefined,
    undefined,
    undefined,
    factory.createIdentifier('ArrayField'),
    undefined,
    [
      factory.createParameterDeclaration(
        undefined,
        undefined,
        undefined,
        factory.createObjectBindingPattern([
          factory.createBindingElement(
            undefined,
            undefined,
            factory.createIdentifier('defaultValues'),
            factory.createArrayLiteralExpression([], false),
          ),
          factory.createBindingElement(undefined, undefined, factory.createIdentifier('onChange'), undefined),
          factory.createBindingElement(undefined, undefined, factory.createIdentifier('inputFieldRef'), undefined),
          factory.createBindingElement(undefined, undefined, factory.createIdentifier('children'), undefined),
          factory.createBindingElement(undefined, undefined, factory.createIdentifier('hasError'), undefined),
          factory.createBindingElement(undefined, undefined, factory.createIdentifier('setFieldValue'), undefined),
          factory.createBindingElement(undefined, undefined, factory.createIdentifier('currentFieldValue'), undefined),
        ]),
        undefined,
        undefined,
        undefined,
      ),
    ],
    undefined,
    factory.createBlock(
      [
        factory.createVariableStatement(
          undefined,
          factory.createVariableDeclarationList(
            [
              factory.createVariableDeclaration(
                factory.createArrayBindingPattern([
                  factory.createBindingElement(
                    undefined,
                    undefined,
                    factory.createIdentifier('selectedBadgeIndex'),
                    undefined,
                  ),
                  factory.createBindingElement(
                    undefined,
                    undefined,
                    factory.createIdentifier('setSelectedBadgeIndex'),
                    undefined,
                  ),
                ]),
                undefined,
                undefined,
                factory.createCallExpression(
                  factory.createPropertyAccessExpression(
                    factory.createIdentifier('React'),
                    factory.createIdentifier('useState'),
                  ),
                  undefined,
                  [],
                ),
              ),
            ],
            NodeFlags.Const,
          ),
        ),
        factory.createVariableStatement(
          undefined,
          factory.createVariableDeclarationList(
            [
              factory.createVariableDeclaration(
                factory.createArrayBindingPattern([
                  factory.createBindingElement(undefined, undefined, factory.createIdentifier('items'), undefined),
                  factory.createBindingElement(undefined, undefined, factory.createIdentifier('setItems'), undefined),
                ]),
                undefined,
                undefined,
                factory.createCallExpression(
                  factory.createPropertyAccessExpression(
                    factory.createIdentifier('React'),
                    factory.createIdentifier('useState'),
                  ),
                  undefined,
                  [factory.createIdentifier('defaultValues')],
                ),
              ),
            ],
            NodeFlags.Const,
          ),
        ),
        factory.createVariableStatement(
          undefined,
          factory.createVariableDeclarationList(
            [
              factory.createVariableDeclaration(
                factory.createIdentifier('removeItem'),
                undefined,
                undefined,
                factory.createArrowFunction(
                  [factory.createModifier(SyntaxKind.AsyncKeyword)],
                  undefined,
                  [
                    factory.createParameterDeclaration(
                      undefined,
                      undefined,
                      undefined,
                      factory.createIdentifier('removeIndex'),
                      undefined,
                      undefined,
                    ),
                  ],
                  undefined,
                  factory.createToken(SyntaxKind.EqualsGreaterThanToken),
                  factory.createBlock(
                    [
                      factory.createVariableStatement(
                        undefined,
                        factory.createVariableDeclarationList(
                          [
                            factory.createVariableDeclaration(
                              factory.createIdentifier('newItems'),
                              undefined,
                              undefined,
                              factory.createCallExpression(
                                factory.createPropertyAccessExpression(
                                  factory.createIdentifier('items'),
                                  factory.createIdentifier('filter'),
                                ),
                                undefined,
                                [
                                  factory.createArrowFunction(
                                    undefined,
                                    undefined,
                                    [
                                      factory.createParameterDeclaration(
                                        undefined,
                                        undefined,
                                        undefined,
                                        factory.createIdentifier('value'),
                                        undefined,
                                        undefined,
                                      ),
                                      factory.createParameterDeclaration(
                                        undefined,
                                        undefined,
                                        undefined,
                                        factory.createIdentifier('index'),
                                        undefined,
                                        undefined,
                                      ),
                                    ],
                                    undefined,
                                    factory.createToken(SyntaxKind.EqualsGreaterThanToken),
                                    factory.createBinaryExpression(
                                      factory.createIdentifier('index'),
                                      factory.createToken(SyntaxKind.ExclamationEqualsEqualsToken),
                                      factory.createIdentifier('removeIndex'),
                                    ),
                                  ),
                                ],
                              ),
                            ),
                          ],
                          NodeFlags.Const,
                        ),
                      ),
                      factory.createExpressionStatement(
                        factory.createAwaitExpression(
                          factory.createCallExpression(factory.createIdentifier('onChange'), undefined, [
                            factory.createIdentifier('newItems'),
                          ]),
                        ),
                      ),
                      factory.createExpressionStatement(
                        factory.createCallExpression(factory.createIdentifier('setSelectedBadgeIndex'), undefined, [
                          factory.createIdentifier('undefined'),
                        ]),
                      ),
                      factory.createExpressionStatement(
                        factory.createCallExpression(factory.createIdentifier('setItems'), undefined, [
                          factory.createIdentifier('newItems'),
                        ]),
                      ),
                    ],
                    true,
                  ),
                ),
              ),
            ],
            NodeFlags.Const,
          ),
        ),
        factory.createVariableStatement(
          undefined,
          factory.createVariableDeclarationList(
            [
              factory.createVariableDeclaration(
                factory.createIdentifier('addItem'),
                undefined,
                undefined,
                factory.createArrowFunction(
                  [factory.createModifier(SyntaxKind.AsyncKeyword)],
                  undefined,
                  [],
                  undefined,
                  factory.createToken(SyntaxKind.EqualsGreaterThanToken),
                  factory.createBlock(
                    [
                      factory.createIfStatement(
                        factory.createBinaryExpression(
                          factory.createPropertyAccessExpression(
                            factory.createIdentifier('currentFieldValue'),
                            factory.createIdentifier('length'),
                          ),
                          factory.createToken(SyntaxKind.AmpersandAmpersandToken),
                          factory.createPrefixUnaryExpression(
                            SyntaxKind.ExclamationToken,
                            factory.createIdentifier('hasError'),
                          ),
                        ),
                        factory.createBlock(
                          [
                            factory.createVariableStatement(
                              undefined,
                              factory.createVariableDeclarationList(
                                [
                                  factory.createVariableDeclaration(
                                    factory.createIdentifier('newItems'),
                                    undefined,
                                    undefined,
                                    factory.createArrayLiteralExpression(
                                      [factory.createSpreadElement(factory.createIdentifier('items'))],
                                      false,
                                    ),
                                  ),
                                ],
                                NodeFlags.Const,
                              ),
                            ),
                            factory.createIfStatement(
                              factory.createBinaryExpression(
                                factory.createIdentifier('selectedBadgeIndex'),
                                factory.createToken(SyntaxKind.ExclamationEqualsEqualsToken),
                                factory.createIdentifier('undefined'),
                              ),
                              factory.createBlock(
                                [
                                  factory.createExpressionStatement(
                                    factory.createBinaryExpression(
                                      factory.createElementAccessExpression(
                                        factory.createIdentifier('newItems'),
                                        factory.createIdentifier('selectedBadgeIndex'),
                                      ),
                                      factory.createToken(SyntaxKind.EqualsToken),
                                      factory.createIdentifier('currentFieldValue'),
                                    ),
                                  ),
                                  factory.createExpressionStatement(
                                    factory.createCallExpression(factory.createIdentifier('setItems'), undefined, [
                                      factory.createIdentifier('newItems'),
                                    ]),
                                  ),
                                  factory.createExpressionStatement(
                                    factory.createCallExpression(
                                      factory.createIdentifier('setSelectedBadgeIndex'),
                                      undefined,
                                      [factory.createIdentifier('undefined')],
                                    ),
                                  ),
                                ],
                                true,
                              ),
                              factory.createBlock(
                                [
                                  factory.createExpressionStatement(
                                    factory.createCallExpression(
                                      factory.createPropertyAccessExpression(
                                        factory.createIdentifier('newItems'),
                                        factory.createIdentifier('push'),
                                      ),
                                      undefined,
                                      [factory.createIdentifier('currentFieldValue')],
                                    ),
                                  ),
                                  factory.createExpressionStatement(
                                    factory.createCallExpression(factory.createIdentifier('setItems'), undefined, [
                                      factory.createIdentifier('newItems'),
                                    ]),
                                  ),
                                ],
                                true,
                              ),
                            ),
                            factory.createExpressionStatement(
                              factory.createAwaitExpression(
                                factory.createCallExpression(factory.createIdentifier('onChange'), undefined, [
                                  factory.createIdentifier('newItems'),
                                ]),
                              ),
                            ),
                          ],
                          true,
                        ),
                        undefined,
                      ),
                    ],
                    true,
                  ),
                ),
              ),
            ],
            NodeFlags.Const,
          ),
        ),
        factory.createReturnStatement(
          factory.createParenthesizedExpression(
            factory.createJsxElement(
              factory.createJsxOpeningElement(
                factory.createPropertyAccessExpression(
                  factory.createIdentifier('React'),
                  factory.createIdentifier('Fragment'),
                ) as JsxTagNamePropertyAccess,
                undefined,
                factory.createJsxAttributes([]),
              ),
              [
                factory.createJsxExpression(undefined, factory.createIdentifier('children')),
                factory.createJsxElement(
                  factory.createJsxOpeningElement(
                    factory.createIdentifier('Flex'),
                    undefined,
                    factory.createJsxAttributes([
                      factory.createJsxAttribute(
                        factory.createIdentifier('justifyContent'),
                        factory.createStringLiteral('flex-end'),
                      ),
                    ]),
                  ),
                  [
                    factory.createJsxElement(
                      factory.createJsxOpeningElement(
                        factory.createIdentifier('Button'),
                        undefined,
                        factory.createJsxAttributes([
                          factory.createJsxAttribute(
                            factory.createIdentifier('children'),
                            factory.createStringLiteral('Cancel'),
                          ),
                          factory.createJsxAttribute(
                            factory.createIdentifier('type'),
                            factory.createStringLiteral('button'),
                          ),
                          factory.createJsxAttribute(
                            factory.createIdentifier('onClick'),
                            factory.createJsxExpression(
                              undefined,
                              factory.createArrowFunction(
                                undefined,
                                undefined,
                                [],
                                undefined,
                                factory.createToken(SyntaxKind.EqualsGreaterThanToken),
                                factory.createBlock(
                                  [
                                    factory.createExpressionStatement(
                                      factory.createCallExpression(
                                        factory.createIdentifier('setFieldValue'),
                                        undefined,
                                        [factory.createStringLiteral('')],
                                      ),
                                    ),
                                  ],
                                  true,
                                ),
                              ),
                            ),
                          ),
                        ]),
                      ),
                      [],
                      factory.createJsxClosingElement(factory.createIdentifier('Button')),
                    ),
                    factory.createJsxElement(
                      factory.createJsxOpeningElement(
                        factory.createIdentifier('Button'),
                        undefined,
                        factory.createJsxAttributes([
                          factory.createJsxAttribute(
                            factory.createIdentifier('children'),
                            factory.createStringLiteral('Save'),
                          ),
                          factory.createJsxAttribute(
                            factory.createIdentifier('variation'),
                            factory.createStringLiteral('primary'),
                          ),
                          factory.createJsxAttribute(
                            factory.createIdentifier('isDisabled'),
                            factory.createJsxExpression(undefined, factory.createIdentifier('hasError')),
                          ),
                          factory.createJsxAttribute(
                            factory.createIdentifier('onClick'),
                            factory.createJsxExpression(undefined, factory.createIdentifier('addItem')),
                          ),
                        ]),
                      ),
                      [],
                      factory.createJsxClosingElement(factory.createIdentifier('Button')),
                    ),
                  ],
                  factory.createJsxClosingElement(factory.createIdentifier('Flex')),
                ),
                factory.createJsxExpression(
                  undefined,
                  factory.createBinaryExpression(
                    factory.createPrefixUnaryExpression(
                      SyntaxKind.ExclamationToken,
                      factory.createPrefixUnaryExpression(
                        SyntaxKind.ExclamationToken,
                        factory.createPropertyAccessExpression(
                          factory.createIdentifier('items'),
                          factory.createIdentifier('length'),
                        ),
                      ),
                    ),
                    factory.createToken(SyntaxKind.AmpersandAmpersandToken),
                    factory.createJsxElement(
                      factory.createJsxOpeningElement(
                        factory.createIdentifier('ScrollView'),
                        undefined,
                        factory.createJsxAttributes([
                          factory.createJsxAttribute(
                            factory.createIdentifier('height'),
                            factory.createStringLiteral('inherit'),
                          ),
                          factory.createJsxAttribute(
                            factory.createIdentifier('width'),
                            factory.createStringLiteral('inherit'),
                          ),
                          factory.createJsxAttribute(
                            factory.createIdentifier('maxHeight'),
                            factory.createJsxExpression(undefined, factory.createStringLiteral('7rem')),
                          ),
                        ]),
                      ),
                      [
                        factory.createJsxExpression(
                          undefined,
                          factory.createCallExpression(
                            factory.createPropertyAccessExpression(
                              factory.createIdentifier('items'),
                              factory.createIdentifier('map'),
                            ),
                            undefined,
                            [
                              factory.createArrowFunction(
                                undefined,
                                undefined,
                                [
                                  factory.createParameterDeclaration(
                                    undefined,
                                    undefined,
                                    undefined,
                                    factory.createIdentifier('value'),
                                    undefined,
                                    undefined,
                                  ),
                                  factory.createParameterDeclaration(
                                    undefined,
                                    undefined,
                                    undefined,
                                    factory.createIdentifier('index'),
                                    undefined,
                                    undefined,
                                  ),
                                ],
                                undefined,
                                factory.createToken(SyntaxKind.EqualsGreaterThanToken),
                                factory.createBlock(
                                  [
                                    factory.createReturnStatement(
                                      factory.createParenthesizedExpression(
                                        factory.createJsxElement(
                                          factory.createJsxOpeningElement(
                                            factory.createIdentifier('Badge'),
                                            undefined,
                                            factory.createJsxAttributes([
                                              factory.createJsxAttribute(
                                                factory.createIdentifier('key'),
                                                factory.createJsxExpression(
                                                  undefined,
                                                  factory.createIdentifier('index'),
                                                ),
                                              ),
                                              factory.createJsxAttribute(
                                                factory.createIdentifier('style'),
                                                factory.createJsxExpression(
                                                  undefined,
                                                  factory.createObjectLiteralExpression(
                                                    [
                                                      factory.createPropertyAssignment(
                                                        factory.createIdentifier('cursor'),
                                                        factory.createStringLiteral('pointer'),
                                                      ),
                                                      factory.createPropertyAssignment(
                                                        factory.createIdentifier('alignItems'),
                                                        factory.createStringLiteral('center'),
                                                      ),
                                                      factory.createPropertyAssignment(
                                                        factory.createIdentifier('marginRight'),
                                                        factory.createNumericLiteral('3'),
                                                      ),
                                                      factory.createPropertyAssignment(
                                                        factory.createIdentifier('marginTop'),
                                                        factory.createNumericLiteral('3'),
                                                      ),
                                                      factory.createPropertyAssignment(
                                                        factory.createIdentifier('backgroundColor'),
                                                        factory.createConditionalExpression(
                                                          factory.createBinaryExpression(
                                                            factory.createIdentifier('index'),
                                                            factory.createToken(SyntaxKind.EqualsEqualsEqualsToken),
                                                            factory.createIdentifier('selectedBadgeIndex'),
                                                          ),
                                                          factory.createToken(SyntaxKind.QuestionToken),
                                                          factory.createStringLiteral('#B8CEF9'),
                                                          factory.createToken(SyntaxKind.ColonToken),
                                                          factory.createStringLiteral(''),
                                                        ),
                                                      ),
                                                    ],
                                                    true,
                                                  ),
                                                ),
                                              ),
                                              factory.createJsxAttribute(
                                                factory.createIdentifier('onClick'),
                                                factory.createJsxExpression(
                                                  undefined,
                                                  factory.createArrowFunction(
                                                    undefined,
                                                    undefined,
                                                    [],
                                                    undefined,
                                                    factory.createToken(SyntaxKind.EqualsGreaterThanToken),
                                                    factory.createBlock(
                                                      [
                                                        factory.createExpressionStatement(
                                                          factory.createCallExpression(
                                                            factory.createIdentifier('setSelectedBadgeIndex'),
                                                            undefined,
                                                            [factory.createIdentifier('index')],
                                                          ),
                                                        ),
                                                        factory.createExpressionStatement(
                                                          factory.createCallExpression(
                                                            factory.createIdentifier('setFieldValue'),
                                                            undefined,
                                                            [
                                                              factory.createElementAccessExpression(
                                                                factory.createIdentifier('items'),
                                                                factory.createIdentifier('index'),
                                                              ),
                                                            ],
                                                          ),
                                                        ),
                                                        factory.createExpressionStatement(
                                                          factory.createCallExpression(
                                                            factory.createPropertyAccessChain(
                                                              factory.createPropertyAccessChain(
                                                                factory.createIdentifier('inputFieldRef'),
                                                                factory.createToken(SyntaxKind.QuestionDotToken),
                                                                factory.createIdentifier('current'),
                                                              ),
                                                              factory.createToken(SyntaxKind.QuestionDotToken),
                                                              factory.createIdentifier('focus'),
                                                            ),
                                                            undefined,
                                                            [],
                                                          ),
                                                        ),
                                                      ],
                                                      true,
                                                    ),
                                                  ),
                                                ),
                                              ),
                                            ]),
                                          ),
                                          [
                                            factory.createJsxExpression(undefined, factory.createIdentifier('value')),
                                            factory.createJsxSelfClosingElement(
                                              factory.createIdentifier('Icon'),
                                              undefined,
                                              factory.createJsxAttributes([
                                                factory.createJsxAttribute(
                                                  factory.createIdentifier('style'),
                                                  factory.createJsxExpression(
                                                    undefined,
                                                    factory.createObjectLiteralExpression(
                                                      [
                                                        factory.createPropertyAssignment(
                                                          factory.createIdentifier('cursor'),
                                                          factory.createStringLiteral('pointer'),
                                                        ),
                                                        factory.createPropertyAssignment(
                                                          factory.createIdentifier('paddingLeft'),
                                                          factory.createNumericLiteral('3'),
                                                        ),
                                                        factory.createPropertyAssignment(
                                                          factory.createIdentifier('width'),
                                                          factory.createNumericLiteral('20'),
                                                        ),
                                                        factory.createPropertyAssignment(
                                                          factory.createIdentifier('height'),
                                                          factory.createNumericLiteral('20'),
                                                        ),
                                                      ],
                                                      true,
                                                    ),
                                                  ),
                                                ),
                                                factory.createJsxAttribute(
                                                  factory.createIdentifier('viewBox'),
                                                  factory.createJsxExpression(
                                                    undefined,
                                                    factory.createObjectLiteralExpression(
                                                      [
                                                        factory.createPropertyAssignment(
                                                          factory.createIdentifier('width'),
                                                          factory.createNumericLiteral('20'),
                                                        ),
                                                        factory.createPropertyAssignment(
                                                          factory.createIdentifier('height'),
                                                          factory.createNumericLiteral('20'),
                                                        ),
                                                      ],
                                                      false,
                                                    ),
                                                  ),
                                                ),
                                                factory.createJsxAttribute(
                                                  factory.createIdentifier('paths'),
                                                  factory.createJsxExpression(
                                                    undefined,
                                                    factory.createArrayLiteralExpression(
                                                      [
                                                        factory.createObjectLiteralExpression(
                                                          [
                                                            factory.createPropertyAssignment(
                                                              factory.createIdentifier('d'),
                                                              factory.createStringLiteral(iconPath),
                                                            ),
                                                            factory.createPropertyAssignment(
                                                              factory.createIdentifier('stroke'),
                                                              factory.createStringLiteral('black'),
                                                            ),
                                                          ],
                                                          true,
                                                        ),
                                                      ],
                                                      true,
                                                    ),
                                                  ),
                                                ),
                                                factory.createJsxAttribute(
                                                  factory.createIdentifier('ariaLabel'),
                                                  factory.createStringLiteral('button'),
                                                ),
                                                factory.createJsxAttribute(
                                                  factory.createIdentifier('onClick'),
                                                  factory.createJsxExpression(
                                                    undefined,
                                                    factory.createArrowFunction(
                                                      undefined,
                                                      undefined,
                                                      [
                                                        factory.createParameterDeclaration(
                                                          undefined,
                                                          undefined,
                                                          undefined,
                                                          factory.createIdentifier('event'),
                                                          undefined,
                                                          undefined,
                                                        ),
                                                      ],
                                                      undefined,
                                                      factory.createToken(SyntaxKind.EqualsGreaterThanToken),
                                                      factory.createBlock(
                                                        [
                                                          factory.createExpressionStatement(
                                                            factory.createCallExpression(
                                                              factory.createPropertyAccessExpression(
                                                                factory.createIdentifier('event'),
                                                                factory.createIdentifier('stopPropagation'),
                                                              ),
                                                              undefined,
                                                              [],
                                                            ),
                                                          ),
                                                          factory.createExpressionStatement(
                                                            factory.createCallExpression(
                                                              factory.createIdentifier('removeItem'),
                                                              undefined,
                                                              [factory.createIdentifier('index')],
                                                            ),
                                                          ),
                                                        ],
                                                        true,
                                                      ),
                                                    ),
                                                  ),
                                                ),
                                              ]),
                                            ),
                                          ],
                                          factory.createJsxClosingElement(factory.createIdentifier('Badge')),
                                        ),
                                      ),
                                    ),
                                  ],
                                  true,
                                ),
                              ),
                            ],
                          ),
                        ),
                      ],
                      factory.createJsxClosingElement(factory.createIdentifier('ScrollView')),
                    ),
                  ),
                ),
                factory.createJsxSelfClosingElement(
                  factory.createIdentifier('Divider'),
                  undefined,
                  factory.createJsxAttributes([
                    factory.createJsxAttribute(
                      factory.createIdentifier('orientation'),
                      factory.createStringLiteral('horizontal'),
                    ),
                    factory.createJsxAttribute(
                      factory.createIdentifier('marginTop'),
                      factory.createJsxExpression(undefined, factory.createNumericLiteral('5')),
                    ),
                  ]),
                ),
              ],
              factory.createJsxClosingElement(
                factory.createPropertyAccessExpression(
                  factory.createIdentifier('React'),
                  factory.createIdentifier('Fragment'),
                ) as JsxTagNamePropertyAccess,
              ),
            ),
          ),
        ),
      ],
      true,
    ),
  );
};
/*
  <ArrayField
    onChange = { async(items) => {
      setModelFields({ ...modelFields, breeds: items });
      setCurrentBreedsValue('');
    }}
    currentBreedsValue = { currentBreedsValue }
    hasError = { errors.breeds?.hasError }
    setFieldValue = { setCurrentBreedsValue }
    inputFieldRef={ breedsRef }
    >
    <ExampleInputField />
  </ArrayField>
 */

export const renderArrayFieldComponent = (fieldName: string, label: string, inputField: JsxChild) =>
  factory.createJsxElement(
    factory.createJsxOpeningElement(
      factory.createIdentifier('ArrayField'),
      undefined,
      factory.createJsxAttributes([
        factory.createJsxAttribute(
          factory.createIdentifier('onChange'),
          factory.createJsxExpression(
            undefined,
            factory.createArrowFunction(
              [factory.createModifier(SyntaxKind.AsyncKeyword)],
              undefined,
              [
                factory.createParameterDeclaration(
                  undefined,
                  undefined,
                  undefined,
                  factory.createIdentifier('items'),
                  undefined,
                  undefined,
                ),
              ],
              undefined,
              factory.createToken(SyntaxKind.EqualsGreaterThanToken),
              factory.createBlock(
                [
                  factory.createExpressionStatement(
                    factory.createCallExpression(
                      factory.createIdentifier(`set${capitalizeFirstLetter(fieldName)}`),
                      undefined,
                      [factory.createIdentifier('items')],
                    ),
                  ),
                  factory.createExpressionStatement(
                    factory.createCallExpression(
                      factory.createIdentifier(`setCurrent${capitalizeFirstLetter(fieldName)}Value`),
                      undefined,
                      [factory.createStringLiteral('')],
                    ),
                  ),
                ],
                true,
              ),
            ),
          ),
        ),
        factory.createJsxAttribute(
          factory.createIdentifier(`currentFieldValue`),
          factory.createJsxExpression(
            undefined,
            factory.createIdentifier(`current${capitalizeFirstLetter(fieldName)}Value`),
          ),
        ),
        factory.createJsxAttribute(
          factory.createIdentifier('hasError'),
          factory.createJsxExpression(
            undefined,
            factory.createPropertyAccessChain(
              factory.createPropertyAccessExpression(
                factory.createIdentifier('errors'),
                factory.createIdentifier(fieldName),
              ),
              factory.createToken(SyntaxKind.QuestionDotToken),
              factory.createIdentifier('hasError'),
            ),
          ),
        ),
        factory.createJsxAttribute(
          factory.createIdentifier('setFieldValue'),
          factory.createJsxExpression(
            undefined,
            factory.createIdentifier(`setCurrent${capitalizeFirstLetter(fieldName)}Value`),
          ),
        ),
        factory.createJsxAttribute(
          factory.createIdentifier('inputFieldRef'),
          factory.createJsxExpression(undefined, factory.createIdentifier(`${lowerCaseFirst(fieldName)}Ref`)),
        ),
      ]),
    ),
    [inputField],
    factory.createJsxClosingElement(factory.createIdentifier('ArrayField')),
  );
