name: Check

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  amplify-cli-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Studio Codegen
        uses: actions/checkout@v2
        with:
          path: amplify-codegen-ui
      - name: Checkout Amplify CLI
        uses: actions/checkout@v2
        with:
          path: amplify-cli
          repository: aws-amplify/amplify-cli
      - name: Setup Node.js LTS
        uses: actions/setup-node@v2
        with:
          node-version: lts/*
      - name: Install amplify-codegen-ui dependencies
        working-directory: amplify-codegen-ui
        run: npm ci
      - name: Lerna bootstrap amplify-codegen-ui
        working-directory: amplify-codegen-ui
        run: lerna bootstrap
      - name: Build amplify-codegen-ui
        working-directory: amplify-codegen-ui
        run: npm run build
      - name: Package amplify-codegen-ui
        working-directory: amplify-codegen-ui
        run: lerna exec npm pack
      - name: Build amplify-cli
        working-directory: amplify-cli
        run: yarn setup-dev
      - name: Install updated codegen libraries
        working-directory: amplify-cli/packages/amplify-util-uibuilder
        run: |
          npm i ../../../amplify-codegen-ui/packages/codegen-ui/aws-amplify-codegen-ui-*.tgz
          npm i ../../../amplify-codegen-ui/packages/codegen-ui-react/aws-amplify-codegen-ui-react-*.tgz
      - name: Test amplify-category-studio
        working-directory: amplify-cli/packages/amplify-util-uibuilder
        run: npm test
      - name: Create a test react app
        run: npx create-react-app e2e-test-app
      - name: Install test app dependencies
        working-directory: e2e-test-app
        run: |
          npm i aws-amplify @aws-amplify/ui-react
          npm i --save-dev cypress
      - name: Run CLI Pull in test app
        working-directory: e2e-test-app
        run: |
          FORCE_RENDER=1 amplify-dev pull --appId ${{ secrets.E2E_TEST_APP_ID }} --envName staging -y --providers "{\
            \"awscloudformation\":{\
              \"configLevel\":\"project\",\
              \"useProfile\":false,\
              \"profileName\":\"default\",\
              \"accessKeyId\":\"${{ secrets.E2E_TEST_ACCESS_KEY }}\",\
              \"secretAccessKey\":\"${{ secrets.E2E_TEST_SECRET_KEY }}\",\
              \"region\":\"us-west-2\"\
            }\
          }"
      - name: Verify Components Are Generated
        working-directory: e2e-test-app
        run: |
          if [ $(ls ./src/ui-components/ | wc -l) -lt 1 ]
          then
            exit 1
          fi
      - name: Write test files
        working-directory: e2e-test-app
        run: cp -r ../amplify-codegen-ui/packages/test-generator/e2e-test-templates/. .
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          working-directory: e2e-test-app
          install: false
          start: npm start
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 120

  functional-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Studio Codegen
        uses: actions/checkout@v2
      - name: Setup Node.js LTS
        uses: actions/setup-node@v2
        with:
          node-version: lts/*
      - name: Install packages
        run: npm ci
      - name: Lerna bootstrap
        run: lerna bootstrap
      - name: Setup Integration Test
        run: npm run integ:setup
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          working-directory: packages/integration-test
          install: false
          start: npm start
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 210
