name: Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  style:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Studio Codegen
        uses: actions/checkout@v2
      - name: Setup Node.js LTS
        uses: actions/setup-node@v2
        with:
          node-version: lts/*
      - name: Install packages
        run: npm ci
      - name: Lerna bootstrap
        run: lerna bootstrap
      - name: Prettier
        run: npm run format:check
      - name: ESLint
        run: npm run lint
      - name: Commit message
        run: |
          echo "${{ github.event.head_commit.message }}" > commit-message-tmp
          ./.husky/commit-msg commit-message-tmp
          rm commit-message-tmp

  unit-test:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: test
    steps:
      - name: Checkout Studio Codegen
        uses: actions/checkout@v2
      - name: Setup Node.js LTS
        uses: actions/setup-node@v2
        with:
          node-version: lts/*
      - name: Install packages
        run: npm ci
      - name: Lerna bootstrap
        run: lerna bootstrap
      - name: Build
        run: npm run build
      - name: Run tests
        run: npm run test

  amplify-category-studio:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Studio Codegen
        uses: actions/checkout@v2
        with:
          path: amplify-codegen-ui-staging
      - name: Checkout Amplify CLI Studio Category
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.DOWNSTREAM }}
          path: amplify-category-studio
          repository: johnpc/amplify-category-studio
      - name: Setup Node.js LTS
        uses: actions/setup-node@v2
        with:
          node-version: lts/*
      - name: Install amplify-codegen-ui-staging dependencies
        working-directory: amplify-codegen-ui-staging
        run: npm ci
      - name: Lerna bootstrap amplify-codegen-ui-staging
        working-directory: amplify-codegen-ui-staging
        run: lerna bootstrap
      - name: Build amplify-codegen-ui-staging
        working-directory: amplify-codegen-ui-staging
        run: npm run build
      - name: Package amplify-codegen-ui-staging
        working-directory: amplify-codegen-ui-staging
        run: lerna exec npm pack
      - name: Install amplify-category-studio
        working-directory: amplify-category-studio
        run: |
          npm install
          npm install amplify-provider-awscloudformation
          npm install aws-sdk.tgz
          npm install ../amplify-codegen-ui-staging/packages/amplify-ui-codegen-schema/amzn-amplify-ui-codegen-schema-0.0.1.tgz
          npm install ../amplify-codegen-ui-staging/packages/studio-ui-codegen/amzn-studio-ui-codegen-0.0.1.tgz
          npm install ../amplify-codegen-ui-staging/packages/studio-ui-codegen-react/amzn-studio-ui-codegen-react-0.0.1.tgz
      - name: Test amplify-category-studio
        working-directory: amplify-category-studio
        run: npm test
